name: Package and release

on:
  push:
    tags:
      - '**'
  schedule:
    - cron: '0 */2 * * *'  # 每2小时的开始执行
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          ref: main  # 选择主分支，或替换为你需要同步的分支
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add the original repository as upstream
        run: |
          git remote add upstream https://github.com/brooklynb7/MeetingStone_Happy.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main

  build:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updated code
        uses: actions/checkout@v3

      - name: Package and release
        uses: BigWigsMods/packager@v2  # 使用适当的打包工具
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

